In [3]:
import pandas as pd

In [4]:
%pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
from sklearn.model_selection import train_test_split
print("✅ Scikit-learn is working!")

✅ Scikit-learn is working!


In [6]:
df=pd.read_csv("loan_data_clean.csv")

In [7]:
df.head(5)

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status,income_log,income_log_capped,debt_income,age_ratio,loan_history
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1,11.183713,11.183713,0.486456,0.000000,11666.666667
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0,9.415971,9.415971,0.081413,0.000000,500.000000
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1,9.428592,9.428592,0.442158,0.120000,1833.333333
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1,11.286702,11.286702,0.438849,0.000000,17500.000000
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1,11.099469,11.099469,0.529213,0.041667,8750.000000


In [8]:
X=df.drop(columns=["loan_status"])

In [9]:
y=df["loan_status"]

In [10]:
X_train , X_test, y_train, y_test = train_test_split(X,y,
                                                     test_size=0.2,
                                                     random_state=42,
                                                     stratify=y,
                                                     shuffle=True
                                                     )

In [11]:
print(f"X_train shape: {X_train.shape} → {X_train.shape[0]} rows, {X_train.shape[1]} columns")
print(f"X_test shape:  {X_test.shape}  → {X_test.shape[0]} rows, {X_test.shape[1]} columns")

X_train shape: (35993, 18) → 35993 rows, 18 columns
X_test shape:  (8999, 18)  → 8999 rows, 18 columns


In [12]:
print(X_test.shape)

(8999, 18)


In [13]:
print(y_train.shape)

(35993,)


In [14]:
print(df['loan_status'].value_counts(normalize=True))

loan_status
0    0.777738
1    0.222262
Name: proportion, dtype: float64


In [15]:
X_train.head(10)

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,income_log,income_log_capped,debt_income,age_ratio,loan_history
28507,29.0,male,Master,76415.0,11,RENT,10000.0,MEDICAL,7.49,0.13,5.0,649,No,11.243947,11.243947,0.130863,0.379310,2000.000000
36435,23.0,female,Associate,66995.0,2,RENT,10000.0,EDUCATION,11.19,0.15,3.0,547,Yes,11.112388,11.112388,0.149263,0.086957,3333.333333
22993,29.0,male,High School,66043.0,6,OWN,20000.0,MEDICAL,18.79,0.30,5.0,539,No,11.098076,11.098076,0.302828,0.206897,4000.000000
31056,44.0,male,High School,81485.0,21,RENT,10000.0,MEDICAL,13.49,0.12,12.0,674,Yes,11.308187,11.308187,0.122720,0.477273,833.333333
22285,29.0,female,Bachelor,116474.0,3,RENT,6400.0,HOMEIMPROVEMENT,11.49,0.05,8.0,651,No,11.665432,11.665432,0.054947,0.103448,800.000000
3689,22.0,female,Associate,22319.0,1,RENT,4000.0,MEDICAL,11.49,0.18,4.0,674,No,10.013238,10.013238,0.179211,0.045455,1000.000000
1839,26.0,male,Associate,121332.0,4,RENT,15000.0,VENTURE,13.49,0.12,4.0,645,No,11.706294,11.706294,0.123627,0.153846,3750.000000
36526,25.0,male,High School,54396.0,4,MORTGAGE,9295.0,DEBTCONSOLIDATION,9.35,0.17,4.0,562,Yes,10.904064,10.904064,0.170873,0.160000,2323.750000
21984,32.0,male,High School,62307.0,9,MORTGAGE,15000.0,DEBTCONSOLIDATION,11.36,0.24,9.0,647,Yes,11.039845,11.039845,0.240740,0.281250,1666.666667
13603,23.0,male,Associate,77586.0,0,RENT,12800.0,EDUCATION,14.35,0.16,4.0,598,No,11.259155,11.259155,0.164976,0.000000,3200.000000


In [16]:
print(y_train.value_counts(normalize=True))

loan_status
0    0.777735
1    0.222265
Name: proportion, dtype: float64


In [17]:
categoricall_columns=['person_gender,person_education,person_home_ownership,loan_intent,previous_loan_defaults_on_file']


In [18]:
from sklearn.preprocessing import OneHotEncoder


encoder=OneHotEncoder(
    sparse_output=False,
    handle_unknown='ignore',
    drop='first'
)

In [19]:
categorical_columns = [
    "person_gender",
    #"person_education",
    "person_home_ownership",
    "loan_intent",
    "previous_loan_defaults_on_file",
    
]

encoder.fit(X_train[categorical_columns])

,"drop drop: {'first', 'if_binary'} or an array-like of shape (n_features,), default=NoneSpecifies a methodology to use to drop one of the categories perfeature. This is useful in situations where perfectly collinearfeatures cause problems, such as when feeding the resulting datainto an unregularized linear regression model.However, dropping one category breaks the symmetry of the originalrepresentation and can therefore induce a bias in downstream models,for instance for penalized linear classification or regression models.- None : retain all features (the default).- 'first' : drop the first category in each feature. If only one category is present, the feature will be dropped entirely.- 'if_binary' : drop the first category in each feature with two categories. Features with 1 or more than 2 categories are left intact.- array : ``drop[i]`` is the category in feature ``X[:, i]`` that should be dropped.When `max_categories` or `min_frequency` is configured to groupinfrequent categories, the dropping behavior is handled after thegrouping... versionadded:: 0.21 The parameter `drop` was added in 0.21... versionchanged:: 0.23 The option `drop='if_binary'` was added in 0.23... versionchanged:: 1.1 Support for dropping infrequent categories.",'first'
,"sparse_output sparse_output: bool, default=TrueWhen ``True``, it returns a SciPy sparse matrix/arrayin ""Compressed Sparse Row"" (CSR) format... versionadded:: 1.2 `sparse` was renamed to `sparse_output`",False
,"handle_unknown handle_unknown: {'error', 'ignore', 'infrequent_if_exist', 'warn'}, default='error'Specifies the way unknown categories are handled during :meth:`transform`.- 'error' : Raise an error if an unknown category is present during transform.- 'ignore' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will be all zeros. In the inverse transform, an unknown category will be denoted as None.- 'infrequent_if_exist' : When an unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will map to the infrequent category if it exists. The infrequent category will be mapped to the last position in the encoding. During inverse transform, an unknown category will be mapped to the category denoted `'infrequent'` if it exists. If the `'infrequent'` category does not exist, then :meth:`transform` and :meth:`inverse_transform` will handle an unknown category as with `handle_unknown='ignore'`. Infrequent categories exist based on `min_frequency` and `max_categories`. Read more in the :ref:`User Guide <encoder_infrequent_categories>`.- 'warn' : When an unknown category is encountered during transform a warning is issued, and the encoding then proceeds as described for `handle_unknown=""infrequent_if_exist""`... versionchanged:: 1.1 `'infrequent_if_exist'` was added to automatically handle unknown categories and infrequent categories... versionadded:: 1.6 The option `""warn""` was added in 1.6.",'ignore'
,"categories categories: 'auto' or a list of array-like, default='auto'Categories (unique values) per feature:- 'auto' : Determine categories automatically from the training data.- list : ``categories[i]`` holds the categories expected in the ith column. The passed categories should not mix strings and numeric values within a single feature, and should be sorted in case of numeric values.The used categories can be found in the ``categories_`` attribute... versionadded:: 0.20",'auto'
,"dtype dtype: number type, default=np.float64Desired dtype of output.",<class 'numpy.float64'>
,"min_frequency min_frequency: int or float, default=NoneSpecifies the minimum frequency below which a category will beconsidered infrequent.- If `int`, categories with a smaller cardinality will be considered infrequent.- If `float`, categories with a smaller cardinality than `min_frequency * n_samples` will be considered infrequent... versionadded:: 1.1 Read more in the :ref:`User Guide <encoder_infre

In [20]:
X_encoded =encoder.transform(X_train[categorical_columns])
X_test_encoded = encoder.transform(X_test[categorical_columns])

In [21]:
name=encoder.get_feature_names_out(categorical_columns)
print(name)

['person_gender_male' 'person_home_ownership_OTHER'
 'person_home_ownership_OWN' 'person_home_ownership_RENT'
 'loan_intent_EDUCATION' 'loan_intent_HOMEIMPROVEMENT'
 'loan_intent_MEDICAL' 'loan_intent_PERSONAL' 'loan_intent_VENTURE'
 'previous_loan_defaults_on_file_Yes']


In [22]:
print(X_encoded)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [1. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 1. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 0. 0. 0.]]


In [23]:
X_encoded_df = pd.DataFrame(X_encoded, 
                                  columns=name, 
                                  index=X_train.index)

X_test_encoded_df = pd.DataFrame(X_test_encoded, 
                                 columns=name, 
                                 index=X_test.index)

In [24]:
from sklearn.preprocessing import OrdinalEncoder 

In [25]:
ordinal_columns=["person_education"]

In [26]:
order_education=["High School","Associate","Bachelor","Master","Doctorate"]

In [27]:
ordinal_encoder=OrdinalEncoder(categories=[order_education])

In [28]:
ordinal_encoder.fit(X_train[ordinal_columns])

,"categories categories: 'auto' or a list of array-like, default='auto'Categories (unique values) per feature:- 'auto' : Determine categories automatically from the training data.- list : ``categories[i]`` holds the categories expected in the ith column. The passed categories should not mix strings and numeric values, and should be sorted in case of numeric values.The used categories can be found in the ``categories_`` attribute.","[['High School', 'Associate', ...]]"
,"dtype dtype: number type, default=np.float64Desired dtype of output.",<class 'numpy.float64'>
,"handle_unknown handle_unknown: {'error', 'use_encoded_value'}, default='error'When set to 'error' an error will be raised in case an unknowncategorical feature is present during transform. When set to'use_encoded_value', the encoded value of unknown categories will beset to the value given for the parameter `unknown_value`. In:meth:`inverse_transform`, an unknown category will be denoted as None... versionadded:: 0.24",'error'
,"unknown_value unknown_value: int or np.nan, default=NoneWhen the parameter handle_unknown is set to 'use_encoded_value', thisparameter is required and will set the encoded value of unknowncategories. It has to be distinct from the values used to encode any ofthe categories in `fit`. If set to np.nan, the `dtype` parameter mustbe a float dtype... versionadded:: 0.24",None
,"encoded_missing_value encoded_missing_value: int or np.nan, default=np.nanEncoded value of missing categories. If set to `np.nan`, then the `dtype`parameter must be a float dtype... versionadded:: 1.1",nan
,"min_frequency min_frequency: int or float, default=NoneSpecifies the minimum frequency below which a category will beconsidered infrequent.- If `int`, categories with a smaller cardinality will be considered infrequent.- If `float`, categories with a smaller cardinality than `min_frequency * n_samples` will be considered infrequent... versionadded:: 1.3 Read more in the :ref:`User Guide <encoder_infrequent_categories>`.",None
,"max_categories max_categories: int, default=NoneSpecifies an upper limit to the number of output categories for each inputfeature when considering infrequent categories. If there are infrequentcategories, `max_categories` includes the category representing theinfrequent categories along with the frequent categories. If `None`,there is no limit to the number of output features.`max_categories` do **not** take into account missing or unknowncategories. Setting `unknown_value` or `encoded_missing_value` to aninteger will increase the number of unique integer codes by one each.This can result in up to `max_categories + 2` integer codes... versionadded:: 1.3 Read more in the :ref:`User Guide <encoder_infrequent_categories>`.",None
Name,Type,Value
categories_ categories_: list of arraysThe categories of each feature determined during ``fit`` (in order ofthe features in X and corresponding with the output of ``transform``).This does not include categories that weren't seen during ``fit``.,list,[array(['High ... dtype=object)]
"feature_names_in_ feature_names_in_: ndarray of shape (`n_features_in_`,)Names of features seen during :term:`fit`. Defined only when `X`has feature names that are all strings... versionadded:: 1.0","ndarray[object](1,)",['person_education']
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`... versionadded:: 1.0,int,1


In [29]:
X_train_ordinal= ordinal_encoder.transform(X_train[ordinal_columns])
X_test_ordinal = ordinal_encoder.transform(X_test[ordinal_columns])

In [30]:
name_encoder = ordinal_encoder.get_feature_names_out(ordinal_columns)

In [31]:
print(name_encoder)

['person_education']


In [32]:
print(X_train_ordinal)

[[3.]
 [1.]
 [0.]
 ...
 [1.]
 [1.]
 [0.]]


In [33]:

X_train_ordinal_df=pd.DataFrame(X_train_ordinal,columns=ordinal_columns, index=X_train.index)
X_test_ordinal_df=pd.DataFrame(X_test_ordinal,columns=ordinal_columns,index=X_test.index)

In [34]:
numerical_columns = [col for col in X_train.columns 
                     if col not in categorical_columns and col not in ordinal_columns]

X_train_num = X_train[numerical_columns]
X_test_num  = X_test[numerical_columns]

In [35]:
X_train_final=pd.concat([X_train_ordinal_df, X_train_num,X_encoded_df],axis=1)

In [36]:
X_test_final=pd.concat([X_test_ordinal_df,X_test_num,X_test_encoded_df], axis=1)

In [37]:
print(X_train_final)

       person_education  person_age  person_income  person_emp_exp  loan_amnt  \
28507               3.0        29.0        76415.0              11    10000.0   
36435               1.0        23.0        66995.0               2    10000.0   
22993               0.0        29.0        66043.0               6    20000.0   
31056               0.0        44.0        81485.0              21    10000.0   
22285               2.0        29.0       116474.0               3     6400.0   
...                 ...         ...            ...             ...        ...   
2934                1.0        26.0       150915.0               2     3000.0   
18279               1.0        29.0        71026.0               8    22000.0   
30133               1.0        41.0        57499.0              19    14000.0   
33017               1.0        22.0        43537.0               0     2161.0   
25682               0.0        33.0       116216.0              10    12000.0   

       loan_int_rate  loan_

In [38]:
print("Original X_train shape:", X_train.shape)
print("Original X_test shape: ", X_test.shape)

Original X_train shape: (35993, 18)
Original X_test shape:  (8999, 18)


In [39]:
print("OneHot columns:", len(categorical_columns))
print("Ordinal columns:", len(ordinal_columns))

OneHot columns: 4
Ordinal columns: 1


In [40]:
print("OneHot encoded shape (train):", X_encoded.shape)
print("Ordinal encoded shape (train):", X_train_ordinal.shape)

OneHot encoded shape (train): (35993, 10)
Ordinal encoded shape (train): (35993, 1)


In [41]:
print("X_train_final shape:", X_train_final.shape)

X_train_final shape: (35993, 24)


In [42]:
print(X_train_final.shape)

(35993, 24)


In [43]:
# === RESET AND RECREATE FINAL DATA ===

# 1. Get numerical columns
numerical_columns = [col for col in X_train.columns 
                     if col not in categorical_columns and col not in ordinal_columns]

# 2. Take the parts (make sure indices are clean)
X_train_num = X_train[numerical_columns].reset_index(drop=True)
X_test_num  = X_test[numerical_columns].reset_index(drop=True)

X_train_onehot_df = X_encoded_df.reset_index(drop=True)
X_test_onehot_df  = X_test_encoded_df.reset_index(drop=True)

X_train_ordinal_df = X_train_ordinal_df.reset_index(drop=True)
X_test_ordinal_df  = X_test_ordinal_df.reset_index(drop=True)

# 3. Combine cleanly
X_train_final = pd.concat([X_train_num, X_train_onehot_df, X_train_ordinal_df], axis=1)
X_test_final  = pd.concat([X_test_num,  X_test_onehot_df,  X_test_ordinal_df],  axis=1)

print("Fixed X_train_final shape:", X_train_final.shape)
print("Fixed X_test_final shape: ", X_test_final.shape)

Fixed X_train_final shape: (35993, 24)
Fixed X_test_final shape:  (8999, 24)


In [44]:
from sklearn.preprocessing import StandardScaler

In [45]:
scaler= StandardScaler()

In [46]:
X_train_scaler=scaler.fit_transform(X_train_final)
X_test_scaler=scaler.transform(X_test_final)

In [47]:
X_train_scaler_df=pd.DataFrame(X_train_scaler,columns=X_train_final.columns,index=X_train_final.index)
X_test_scaler_df=pd.DataFrame(X_test_scaler,columns=X_test_final.columns,index=X_test_final.index)

In [48]:
print(X_train_scaler_df.shape)

(35993, 24)


In [49]:
print(X_test_scaler_df.shape)

(8999, 24)


In [50]:
print(X_train_scaler_df.head)

<bound method NDFrame.head of        person_age  person_income  person_emp_exp  loan_amnt  loan_int_rate  \
0        0.212513      -0.056052        0.946401   0.069584      -1.179409   
1       -0.803354      -0.202814       -0.573099   0.069584       0.061842   
2        0.212513      -0.217646        0.102234   1.660325       2.611438   
3        2.752179       0.022938        2.634735   0.069584       0.833430   
4        0.212513       0.568061       -0.404266  -0.503084       0.162484   
...           ...            ...             ...        ...            ...   
35988   -0.295421       1.104646       -0.573099  -1.043936       0.404024   
35989    0.212513      -0.140012        0.439901   1.978474       0.893815   
35990    2.244245      -0.350760        2.297069   0.705880      -1.048575   
35991   -0.972665      -0.568286       -0.910766  -1.177399      -1.176054   
35992    0.889757       0.564041        0.777568   0.387732       1.568116   

       loan_percent_income  cb_pe

In [51]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd

In [52]:
models = {
    "1. Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "2. KNN": KNeighborsClassifier(n_neighbors=5),
    "3. Decision Tree": DecisionTreeClassifier(max_depth=6, random_state=42),
    "4. Random Forest": RandomForestClassifier(n_estimators=100, max_depth=8, random_state=42)
}

In [53]:
results=[]

In [54]:
for name, model in models.items():
    print(name)

1. Logistic Regression
2. KNN
3. Decision Tree
4. Random Forest


In [55]:
model.fit(X_train_scaler_df,y_train)

,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",8
,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap:

In [56]:
y_predict=model.predict(X_test_scaler_df)

In [57]:
results = []
for name,model in models.items():
    
    model.fit(X_train_scaler_df,y_train)          # Train

    y_pred=model.predict(X_test_scaler)
          # Predict on test
    acc = accuracy_score(y_test,y_pred)
   # acc = accuracy_score(y_test, y_pred)
    print(f"{name} Accuracy: {acc:.4f}")
    
    results.append({"Model": name, "Accuracy": acc})
    
    if acc > 0.85:
        print(classification_report(y_test, y_pred))
        print("-" * 60)

# Final comparison
results_df = pd.DataFrame(results)
print("\n=== Model Comparison ===")
print(results_df.sort_values(by="Accuracy", ascending=False))

c:\Users\Azeb\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
c:\Users\Azeb\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


1. Logistic Regression Accuracy: 0.9008
              precision    recall  f1-score   support

           0       0.93      0.94      0.94      6999
           1       0.79      0.76      0.77      2000

    accuracy                           0.90      8999
   macro avg       0.86      0.85      0.85      8999
weighted avg       0.90      0.90      0.90      8999

------------------------------------------------------------
2. KNN Accuracy: 0.9000
              precision    recall  f1-score   support

           0       0.92      0.95      0.94      6999
           1       0.80      0.73      0.76      2000

    accuracy                           0.90      8999
   macro avg       0.86      0.84      0.85      8999
weighted avg       0.90      0.90      0.90      8999

------------------------------------------------------------


c:\Users\Azeb\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


3. Decision Tree Accuracy: 0.9132
              precision    recall  f1-score   support

           0       0.93      0.96      0.95      6999
           1       0.85      0.74      0.79      2000

    accuracy                           0.91      8999
   macro avg       0.89      0.85      0.87      8999
weighted avg       0.91      0.91      0.91      8999

------------------------------------------------------------
4. Random Forest Accuracy: 0.9189
              precision    recall  f1-score   support

           0       0.92      0.99      0.95      6999
           1       0.93      0.68      0.79      2000

    accuracy                           0.92      8999
   macro avg       0.93      0.83      0.87      8999
weighted avg       0.92      0.92      0.91      8999

------------------------------------------------------------

=== Model Comparison ===
                    Model  Accuracy
3        4. Random Forest  0.918880
2        3. Decision Tree  0.913213
0  1. Logistic Regress

c:\Users\Azeb\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [58]:
# ahun le randome forest lsra esun new best gin meshashal yfelgal so lesu lsra
model = {"Random Forest": RandomForestClassifier(n_estimators=300, max_depth=15, random_state=42,min_samples_split=10,
    min_samples_leaf=5,class_weight="balanced")}

In [59]:
result=[]
for name,model in model.items():
    
    model.fit(X_train_scaler_df,y_train)
    y_pre=model.predict(X_test_scaler)
    accu=accuracy_score(y_test,y_pre)
    print(accu)
    result.append({"Model": name, "Accuracy": accu})

if accu > 0.85:

 print(classification_report(y_test,y_pre))
print("-" * 60)
result_df=pd.DataFrame(result)
print(result_df)



c:\Users\Azeb\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


0.9134348260917879
              precision    recall  f1-score   support

           0       0.97      0.91      0.94      6999
           1       0.75      0.91      0.82      2000

    accuracy                           0.91      8999
   macro avg       0.86      0.91      0.88      8999
weighted avg       0.92      0.91      0.92      8999

------------------------------------------------------------
           Model  Accuracy
0  Random Forest  0.913435


In [60]:
from xgboost import XGBClassifier

In [61]:
xgb = XGBClassifier(random_state=42,n_estimators=300,      # Number of boosting trees
    max_depth=6,           # Maximum depth of each tree
    learning_rate=0.1,     # How much each tree contributes
    subsample=0.8,         # Fraction of training rows used per tree
    colsample_bytree=0.8, ) # Fraction of features used per tree)

In [62]:
xgb.fit(X_train_scaler_df,y_train)

,"base_score base_score: typing.Union[float, typing.List[float], NoneType]The initial prediction score of all instances, global bias.",None
,booster,None
,"callbacks callbacks: typing.Optional[typing.List[xgboost.callback.TrainingCallback]]List of callback functions that are applied at end of each iteration.It is possible to use predefined callbacks by using:ref:`Callback API <callback_api>`... note:: States in callback are not preserved during training, which means callback objects can not be reused for multiple training sessions without reinitialization or deepcopy... code-block:: python for params in parameters_grid: # be sure to (re)initialize the callbacks before each run callbacks = [xgb.callback.LearningRateScheduler(custom_rates)] reg = xgboost.XGBRegressor(**params, callbacks=callbacks) reg.fit(X, y)",None
,colsample_bylevel colsample_bylevel: typing.Optional[float]Subsample ratio of columns for each level.,None
,colsample_bynode colsample_bynode: typing.Optional[float]Subsample ratio of columns for each split.,None
,colsample_bytree colsample_bytree: typing.Optional[float]Subsample ratio of columns when constructing each tree.,0.8
,"device device: typing.Optional[str].. versionadded:: 2.0.0Device ordinal, available options are `cpu`, `cuda`, and `gpu`.",None
,"early_stopping_rounds early_stopping_rounds: typing.Optional[int].. versionadded:: 1.6.0- Activates early stopping. Validation metric needs to improve at least once in every **early_stopping_rounds** round(s) to continue training. Requires at least one item in **eval_set** in :py:meth:`fit`.- If early stopping occurs, the model will have two additional attributes: :py:attr:`best_score` and :py:attr:`best_iteration`. These are used by the :py:meth:`predict` and :py:meth:`apply` methods to determine the optimal number of trees during inference. If users want to access the full model (including trees built after early stopping), they can specify the `iteration_range` in these inference methods. In addition, other utilities like model plotting can also use the entire model.- If you prefer to discard the trees after `best_iteration`, consider using the callback function :py:class:`xgboost.callback.EarlyStopping`.- If there's more than one item in **eval_set**, the last entry will be used for early stopping. If there's more than one metric in **eval_metric**, the last metric will be used for early stopping.",None
,enable_categorical enable_categorical: boolSee the same parameter of :py:class:`DMatrix` for details.,False
,"eval_metric eval_metric: typing.Union[str, typing.List[typing.Union[str, typing.Callable]], typing.Callable, NoneType].. versionadded:: 1.6.0Metric used for monitoring the training result and early stopping. It can be astring or list of strings as names of predefined metric in XGBoost (See:doc:`/parameter`), one of the metrics in :py:mod:`sklearn.metrics`, or anyother user defined metric that looks like `sklearn.metrics`.If custom objective is also provided, then custom metric should implement thecorresponding reverse link function.Unlike the `scoring` parameter commonly used in scikit-learn, when a callableobject is provided, it's assumed to be a cost function and by default XGBoostwill minimize the result during early stopping.For advanced usage on Early stopping like directly choosing to maximize insteadof minimize, see :py:obj:`xgboost.callback.EarlyStopping`.See :doc:`/tutorials/custom_metric_obj` and :ref:`custom-obj-metric` for moreinformation... code-block:: python from sklearn.datasets import load_diabetes from sklearn.metrics import mean_absolute_error X, y = load_diabetes(return_X_y=True) reg = xgb.XGBRegressor( tree_method=""hist"", eval_metric=mean_absolute_error, ) reg.fit(X, y, eval_set=[(X, y)])",None
,feature_types feature_types: typing.Optional[typing.Sequence[str]].. versionadded:: 1.7.0Used for specifying feature types without constructing a dataframe. Seethe :py:class:`DMatrix` for details.,None


In [63]:
xgb_pred=xgb.predict(X_test_scaler_df)

In [64]:
print(xgb_pred)

[0 1 0 ... 0 0 0]


In [65]:
accuracy_of_xgb= accuracy_score(y_test,xgb_pred)

In [66]:
print(accuracy_of_xgb)

0.9374374930547839


In [67]:
print(classification_report(y_test,xgb_pred))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96      6999
           1       0.89      0.81      0.85      2000

    accuracy                           0.94      8999
   macro avg       0.92      0.89      0.91      8999
weighted avg       0.94      0.94      0.94      8999



In [68]:
from sklearn.metrics import  confusion_matrix

In [69]:
cm=confusion_matrix(y_test,xgb_pred)
print(cm)

[[6806  193]
 [ 370 1630]]


In [70]:
from sklearn.metrics import  roc_curve, roc_auc_score

In [71]:
y_prob = xgb.predict_proba(X_test_scaler_df)[:,1]

In [72]:
auc = roc_auc_score(y_test,y_prob)

In [73]:
print(auc)

0.979540577225318


In [74]:
from sklearn.model_selection import cross_val_score

In [75]:
scores = cross_val_score(xgb,X_train_scaler_df,y_train,cv=5,scoring="accuracy")

In [76]:
print(scores)

[0.93360189 0.93068482 0.93624114 0.93553765 0.93553765]


In [77]:
print(scores.mean())

0.9343206299569022


In [78]:
print(scores.std())

0.0020192261221220133


In [79]:
from sklearn.model_selection import RandomizedSearchCV

In [80]:
xgb = XGBClassifier(random_state=42)

In [ ]:
param_dist =  {
"n_estimators": [100,200,300,400,500],
    "max_depth": [3,5,7,9],
    "learning_rate": [0.01,0.05,0.1],
    "subsample": [0.7,0.8,0.9,1.0], # kalew ye training data wust 0.7 means 70 % ye traing sample yiteqemal
    "colsample_bytree": [0.6,0.8,1.0] # yalewn feature sample yiteqemal maletim 0.6 means 60% feature yiteqemal(income,age..)
}

In [ ]:
para_search=RandomizedSearchCV(estimator=xgb,#yhe yaw minfelgew model new random forestm mehon yicilal gin yhegnaw xgboost lezi arif new 
                               param_distributions=param_dist, # yhe demo search mideregew data set new param_dist 
                               n_iter=20, # 20 random combination select yaregal
                               cv=5,
                               scoring="roc_auc",
                               random_state=42,
                               n_jobs=-1 # cpu yalewn hulu enditeqem new yhe 
)

In [83]:
para_search.fit(X_train_scaler_df,y_train)

,"estimator estimator: estimator objectAn object of that type is instantiated for each grid point.This is assumed to implement the scikit-learn estimator interface.Either estimator needs to provide a ``score`` function,or ``scoring`` must be passed.","XGBClassifier...ree=None, ...)"
,"param_distributions param_distributions: dict or list of dictsDictionary with parameters names (`str`) as keys and distributionsor lists of parameters to try. Distributions must provide a ``rvs``method for sampling (such as those from scipy.stats.distributions).If a list is given, it is sampled uniformly.If a list of dicts is given, first a dict is sampled uniformly, andthen a parameter is sampled using that dict as above.","{'colsample_bytree': [0.6, 0.8, ...], 'learning_rate': [0.01, 0.05, ...], 'max_depth': [3, 5, ...], 'n_estimators': [100, 200, ...], ...}"
,"n_iter n_iter: int, default=10Number of parameter settings that are sampled. n_iter tradesoff runtime vs quality of the solution.",20
,"scoring scoring: str, callable, list, tuple or dict, default=NoneStrategy to evaluate the performance of the cross-validated model onthe test set.If `scoring` represents a single score, one can use:- a single string (see :ref:`scoring_string_names`);- a callable (see :ref:`scoring_callable`) that returns a single value;- `None`, the `estimator`'s :ref:`default evaluation criterion <scoring_api_overview>` is used.If `scoring` represents multiple scores, one can use:- a list or tuple of unique strings;- a callable returning a dictionary where the keys are the metric names and the values are the metric scores;- a dictionary with metric names as keys and callables as values.See :ref:`multimetric_grid_search` for an example.If None, the estimator's score method is used.",'roc_auc'
,"n_jobs n_jobs: int, default=NoneNumber of jobs to run in parallel.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details... versionchanged:: v0.20 `n_jobs` default changed from 1 to None",-1
,"cv cv: int, cross-validation generator or an iterable, default=NoneDetermines the cross-validation splitting strategy.Possible inputs for cv are:- None, to use the default 5-fold cross validation,- integer, to specify the number of folds in a `(Stratified)KFold`,- :term:`CV splitter`,- an iterable yielding (train, test) splits as arrays of indices.For integer/None inputs, if the estimator is a classifier and ``y`` iseither binary or multiclass, :class:`StratifiedKFold` is used. In allother cases, :class:`KFold` is used. These splitters are instantiatedwith `shuffle=False` so the splits will be the same across calls.Refer :ref:`User Guide <cross_validation>` for the variouscross-validation strategies that can be used here... versionchanged:: 0.22 ``cv`` default value if None changed from 3-fold to 5-fold.",5
,"random_state random_state: int, RandomState instance or None, default=NonePseudo random number generator state used for random uniform samplingfrom lists of possible values instead of scipy.stats distributions.Pass an int for reproducible output across multiplefunction calls.See :term:`Glossary <random_state>`.",42
,"refit refit: bool, str, or callable, default=TrueRefit an estimator using the best found parameters on the wholedataset.For multiple metric evaluation, this needs to be a `str` denoting thescorer that would be used to find the best parameters for refittingthe estimator at the end.Where there are considerations other than maximum score inchoosing a best estimator, ``refit`` can be set to a function whichreturns the selected ``best_index_`` given the ``cv_results_``. In thatcase, the ``best_estimator_`` and ``best_params_`` will be setaccording to the returned ``best_index_`` while the ``best_score_``attribute will not be available.The refitted estimator is made available at the ``best_estimator_``attribute and permits using ``predict`` directly on this``RandomizedSearchCV`` instance

In [84]:
print(para_search.best_estimator_)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.6, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.1, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=500,
              n_jobs=None, num_parallel_tree=None, ...)


In [85]:
print(para_search.best_params_)

{'subsample': 0.9, 'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.1, 'colsample_bytree': 0.6}


In [86]:
print(para_search.best_score_)

0.9791841274225908


In [ ]:
best_xgb=para_search.best_estimator_   # best yehonewn xgb model agegenew maletim manually ye hyperparametrochun number kemiqeyer beqelalu ezi gar best trained yehonewn xgb magnet ecilalew 

In [ ]:
y_pred=best_xgb.predict(X_test_scaler_df) # 
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96      6999
           1       0.89      0.81      0.85      2000

    accuracy                           0.94      8999
   macro avg       0.92      0.89      0.91      8999
weighted avg       0.94      0.94      0.94      8999



In [90]:
import joblib

In [91]:
joblib.dump(best_xgb,"credit-risk-model.pkl")

['credit-risk-model.pkl']

In [94]:
joblib.dump(scaler,"scaler.pkl")

['scaler.pkl']

In [95]:
print(X_train.columns.tolist())

['person_age', 'person_gender', 'person_education', 'person_income', 'person_emp_exp', 'person_home_ownership', 'loan_amnt', 'loan_intent', 'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length', 'credit_score', 'previous_loan_defaults_on_file', 'income_log', 'income_log_capped', 'debt_income', 'age_ratio', 'loan_history']
